// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package v1

import (
	"context"
	"fmt"
)

type Session struct {
	AccountUid   string `thrift:"account_uid,1" frugal:"1,default,string" json:"account_uid"`
	AccessToken  string `thrift:"access_token,2" frugal:"2,default,string" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,3" frugal:"3,default,string" json:"refresh_token"`
	ExpiresAt    string `thrift:"expires_at,4" frugal:"4,default,string" json:"expires_at"`
}

func NewSession() *Session {
	return &Session{}
}

func (p *Session) InitDefault() {
}

func (p *Session) GetAccountUid() (v string) {
	return p.AccountUid
}

func (p *Session) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *Session) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *Session) GetExpiresAt() (v string) {
	return p.ExpiresAt
}
func (p *Session) SetAccountUid(val string) {
	p.AccountUid = val
}
func (p *Session) SetAccessToken(val string) {
	p.AccessToken = val
}
func (p *Session) SetRefreshToken(val string) {
	p.RefreshToken = val
}
func (p *Session) SetExpiresAt(val string) {
	p.ExpiresAt = val
}

func (p *Session) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Session(%+v)", *p)
}

var fieldIDToName_Session = map[int16]string{
	1: "account_uid",
	2: "access_token",
	3: "refresh_token",
	4: "expires_at",
}

type RegisterRequest struct {
	Email       string `thrift:"email,1" frugal:"1,default,string" json:"email"`
	Password    string `thrift:"password,2" frugal:"2,default,string" json:"password"`
	DisplayName string `thrift:"display_name,3" frugal:"3,default,string" json:"display_name"`
	DeviceUid   string `thrift:"device_uid,4" frugal:"4,default,string" json:"device_uid"`
	DeviceName  string `thrift:"device_name,5" frugal:"5,default,string" json:"device_name"`
	Platform    string `thrift:"platform,6" frugal:"6,default,string" json:"platform"`
}

func NewRegisterRequest() *RegisterRequest {
	return &RegisterRequest{}
}

func (p *RegisterRequest) InitDefault() {
}

func (p *RegisterRequest) GetEmail() (v string) {
	return p.Email
}

func (p *RegisterRequest) GetPassword() (v string) {
	return p.Password
}

func (p *RegisterRequest) GetDisplayName() (v string) {
	return p.DisplayName
}

func (p *RegisterRequest) GetDeviceUid() (v string) {
	return p.DeviceUid
}

func (p *RegisterRequest) GetDeviceName() (v string) {
	return p.DeviceName
}

func (p *RegisterRequest) GetPlatform() (v string) {
	return p.Platform
}
func (p *RegisterRequest) SetEmail(val string) {
	p.Email = val
}
func (p *RegisterRequest) SetPassword(val string) {
	p.Password = val
}
func (p *RegisterRequest) SetDisplayName(val string) {
	p.DisplayName = val
}
func (p *RegisterRequest) SetDeviceUid(val string) {
	p.DeviceUid = val
}
func (p *RegisterRequest) SetDeviceName(val string) {
	p.DeviceName = val
}
func (p *RegisterRequest) SetPlatform(val string) {
	p.Platform = val
}

func (p *RegisterRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterRequest(%+v)", *p)
}

var fieldIDToName_RegisterRequest = map[int16]string{
	1: "email",
	2: "password",
	3: "display_name",
	4: "device_uid",
	5: "device_name",
	6: "platform",
}

type RegisterResponse struct {
	Session *Session `thrift:"session,1,optional" frugal:"1,optional,Session" json:"session,omitempty"`
}

func NewRegisterResponse() *RegisterResponse {
	return &RegisterResponse{}
}

func (p *RegisterResponse) InitDefault() {
}

var RegisterResponse_Session_DEFAULT *Session

func (p *RegisterResponse) GetSession() (v *Session) {
	if !p.IsSetSession() {
		return RegisterResponse_Session_DEFAULT
	}
	return p.Session
}
func (p *RegisterResponse) SetSession(val *Session) {
	p.Session = val
}

func (p *RegisterResponse) IsSetSession() bool {
	return p.Session != nil
}

func (p *RegisterResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResponse(%+v)", *p)
}

var fieldIDToName_RegisterResponse = map[int16]string{
	1: "session",
}

type LoginRequest struct {
	Email      string `thrift:"email,1" frugal:"1,default,string" json:"email"`
	Password   string `thrift:"password,2" frugal:"2,default,string" json:"password"`
	DeviceUid  string `thrift:"device_uid,3" frugal:"3,default,string" json:"device_uid"`
	DeviceName string `thrift:"device_name,4" frugal:"4,default,string" json:"device_name"`
	Platform   string `thrift:"platform,5" frugal:"5,default,string" json:"platform"`
}

func NewLoginRequest() *LoginRequest {
	return &LoginRequest{}
}

func (p *LoginRequest) InitDefault() {
}

func (p *LoginRequest) GetEmail() (v string) {
	return p.Email
}

func (p *LoginRequest) GetPassword() (v string) {
	return p.Password
}

func (p *LoginRequest) GetDeviceUid() (v string) {
	return p.DeviceUid
}

func (p *LoginRequest) GetDeviceName() (v string) {
	return p.DeviceName
}

func (p *LoginRequest) GetPlatform() (v string) {
	return p.Platform
}
func (p *LoginRequest) SetEmail(val string) {
	p.Email = val
}
func (p *LoginRequest) SetPassword(val string) {
	p.Password = val
}
func (p *LoginRequest) SetDeviceUid(val string) {
	p.DeviceUid = val
}
func (p *LoginRequest) SetDeviceName(val string) {
	p.DeviceName = val
}
func (p *LoginRequest) SetPlatform(val string) {
	p.Platform = val
}

func (p *LoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginRequest(%+v)", *p)
}

var fieldIDToName_LoginRequest = map[int16]string{
	1: "email",
	2: "password",
	3: "device_uid",
	4: "device_name",
	5: "platform",
}

type LoginResponse struct {
	Session *Session `thrift:"session,1,optional" frugal:"1,optional,Session" json:"session,omitempty"`
}

func NewLoginResponse() *LoginResponse {
	return &LoginResponse{}
}

func (p *LoginResponse) InitDefault() {
}

var LoginResponse_Session_DEFAULT *Session

func (p *LoginResponse) GetSession() (v *Session) {
	if !p.IsSetSession() {
		return LoginResponse_Session_DEFAULT
	}
	return p.Session
}
func (p *LoginResponse) SetSession(val *Session) {
	p.Session = val
}

func (p *LoginResponse) IsSetSession() bool {
	return p.Session != nil
}

func (p *LoginResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResponse(%+v)", *p)
}

var fieldIDToName_LoginResponse = map[int16]string{
	1: "session",
}

type RefreshSessionRequest struct {
	RefreshToken string `thrift:"refresh_token,1" frugal:"1,default,string" json:"refresh_token"`
	DeviceUid    string `thrift:"device_uid,2" frugal:"2,default,string" json:"device_uid"`
}

func NewRefreshSessionRequest() *RefreshSessionRequest {
	return &RefreshSessionRequest{}
}

func (p *RefreshSessionRequest) InitDefault() {
}

func (p *RefreshSessionRequest) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *RefreshSessionRequest) GetDeviceUid() (v string) {
	return p.DeviceUid
}
func (p *RefreshSessionRequest) SetRefreshToken(val string) {
	p.RefreshToken = val
}
func (p *RefreshSessionRequest) SetDeviceUid(val string) {
	p.DeviceUid = val
}

func (p *RefreshSessionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshSessionRequest(%+v)", *p)
}

var fieldIDToName_RefreshSessionRequest = map[int16]string{
	1: "refresh_token",
	2: "device_uid",
}

type RefreshSessionResponse struct {
	Session *Session `thrift:"session,1,optional" frugal:"1,optional,Session" json:"session,omitempty"`
}

func NewRefreshSessionResponse() *RefreshSessionResponse {
	return &RefreshSessionResponse{}
}

func (p *RefreshSessionResponse) InitDefault() {
}

var RefreshSessionResponse_Session_DEFAULT *Session

func (p *RefreshSessionResponse) GetSession() (v *Session) {
	if !p.IsSetSession() {
		return RefreshSessionResponse_Session_DEFAULT
	}
	return p.Session
}
func (p *RefreshSessionResponse) SetSession(val *Session) {
	p.Session = val
}

func (p *RefreshSessionResponse) IsSetSession() bool {
	return p.Session != nil
}

func (p *RefreshSessionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshSessionResponse(%+v)", *p)
}

var fieldIDToName_RefreshSessionResponse = map[int16]string{
	1: "session",
}

type ClientVersion struct {
	Ts  string `thrift:"ts,1" frugal:"1,default,string" json:"ts"`
	Ctr int32  `thrift:"ctr,2" frugal:"2,default,i32" json:"ctr"`
	Dev string `thrift:"dev,3" frugal:"3,default,string" json:"dev"`
}

func NewClientVersion() *ClientVersion {
	return &ClientVersion{}
}

func (p *ClientVersion) InitDefault() {
}

func (p *ClientVersion) GetTs() (v string) {
	return p.Ts
}

func (p *ClientVersion) GetCtr() (v int32) {
	return p.Ctr
}

func (p *ClientVersion) GetDev() (v string) {
	return p.Dev
}
func (p *ClientVersion) SetTs(val string) {
	p.Ts = val
}
func (p *ClientVersion) SetCtr(val int32) {
	p.Ctr = val
}
func (p *ClientVersion) SetDev(val string) {
	p.Dev = val
}

func (p *ClientVersion) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ClientVersion(%+v)", *p)
}

var fieldIDToName_ClientVersion = map[int16]string{
	1: "ts",
	2: "ctr",
	3: "dev",
}

type ServerVersion struct {
	ChangeId    int64  `thrift:"change_id,1" frugal:"1,default,i64" json:"change_id"`
	CommittedAt string `thrift:"committed_at,2" frugal:"2,default,string" json:"committed_at"`
}

func NewServerVersion() *ServerVersion {
	return &ServerVersion{}
}

func (p *ServerVersion) InitDefault() {
}

func (p *ServerVersion) GetChangeId() (v int64) {
	return p.ChangeId
}

func (p *ServerVersion) GetCommittedAt() (v string) {
	return p.CommittedAt
}
func (p *ServerVersion) SetChangeId(val int64) {
	p.ChangeId = val
}
func (p *ServerVersion) SetCommittedAt(val string) {
	p.CommittedAt = val
}

func (p *ServerVersion) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServerVersion(%+v)", *p)
}

var fieldIDToName_ServerVersion = map[int16]string{
	1: "change_id",
	2: "committed_at",
}

type SubTask struct {
	Id          string `thrift:"id,1" frugal:"1,default,string" json:"id"`
	Content     string `thrift:"content,2" frugal:"2,default,string" json:"content"`
	IsCompleted bool   `thrift:"is_completed,3" frugal:"3,default,bool" json:"is_completed"`
	SortOrder   int32  `thrift:"sort_order,4" frugal:"4,default,i32" json:"sort_order"`
	CreatedAt   string `thrift:"created_at,5" frugal:"5,default,string" json:"created_at"`
	UpdatedAt   string `thrift:"updated_at,6" frugal:"6,default,string" json:"updated_at"`
}

func NewSubTask() *SubTask {
	return &SubTask{}
}

func (p *SubTask) InitDefault() {
}

func (p *SubTask) GetId() (v string) {
	return p.Id
}

func (p *SubTask) GetContent() (v string) {
	return p.Content
}

func (p *SubTask) GetIsCompleted() (v bool) {
	return p.IsCompleted
}

func (p *SubTask) GetSortOrder() (v int32) {
	return p.SortOrder
}

func (p *SubTask) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *SubTask) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}
func (p *SubTask) SetId(val string) {
	p.Id = val
}
func (p *SubTask) SetContent(val string) {
	p.Content = val
}
func (p *SubTask) SetIsCompleted(val bool) {
	p.IsCompleted = val
}
func (p *SubTask) SetSortOrder(val int32) {
	p.SortOrder = val
}
func (p *SubTask) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *SubTask) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}

func (p *SubTask) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SubTask(%+v)", *p)
}

var fieldIDToName_SubTask = map[int16]string{
	1: "id",
	2: "content",
	3: "is_completed",
	4: "sort_order",
	5: "created_at",
	6: "updated_at",
}

type DeadlineDocument struct {
	Uid             string     `thrift:"uid,1" frugal:"1,default,string" json:"uid"`
	LegacyId        int64      `thrift:"legacy_id,2" frugal:"2,default,i64" json:"legacy_id"`
	Name            string     `thrift:"name,3" frugal:"3,default,string" json:"name"`
	StartTime       string     `thrift:"start_time,4" frugal:"4,default,string" json:"start_time"`
	EndTime         string     `thrift:"end_time,5" frugal:"5,default,string" json:"end_time"`
	State           string     `thrift:"state,6" frugal:"6,default,string" json:"state"`
	CompleteTime    string     `thrift:"complete_time,7" frugal:"7,default,string" json:"complete_time"`
	Note            string     `thrift:"note,8" frugal:"8,default,string" json:"note"`
	IsStared        bool       `thrift:"is_stared,9" frugal:"9,default,bool" json:"is_stared"`
	Type            string     `thrift:"type,10" frugal:"10,default,string" json:"type"`
	HabitCount      int32      `thrift:"habit_count,11" frugal:"11,default,i32" json:"habit_count"`
	HabitTotalCount int32      `thrift:"habit_total_count,12" frugal:"12,default,i32" json:"habit_total_count"`
	CalendarEvent   int64      `thrift:"calendar_event,13" frugal:"13,default,i64" json:"calendar_event"`
	Timestamp       string     `thrift:"timestamp,14" frugal:"14,default,string" json:"timestamp"`
	SubTasks        []*SubTask `thrift:"sub_tasks,15" frugal:"15,default,list<SubTask>" json:"sub_tasks"`
}

func NewDeadlineDocument() *DeadlineDocument {
	return &DeadlineDocument{}
}

func (p *DeadlineDocument) InitDefault() {
}

func (p *DeadlineDocument) GetUid() (v string) {
	return p.Uid
}

func (p *DeadlineDocument) GetLegacyId() (v int64) {
	return p.LegacyId
}

func (p *DeadlineDocument) GetName() (v string) {
	return p.Name
}

func (p *DeadlineDocument) GetStartTime() (v string) {
	return p.StartTime
}

func (p *DeadlineDocument) GetEndTime() (v string) {
	return p.EndTime
}

func (p *DeadlineDocument) GetState() (v string) {
	return p.State
}

func (p *DeadlineDocument) GetCompleteTime() (v string) {
	return p.CompleteTime
}

func (p *DeadlineDocument) GetNote() (v string) {
	return p.Note
}

func (p *DeadlineDocument) GetIsStared() (v bool) {
	return p.IsStared
}

func (p *DeadlineDocument) GetType() (v string) {
	return p.Type
}

func (p *DeadlineDocument) GetHabitCount() (v int32) {
	return p.HabitCount
}

func (p *DeadlineDocument) GetHabitTotalCount() (v int32) {
	return p.HabitTotalCount
}

func (p *DeadlineDocument) GetCalendarEvent() (v int64) {
	return p.CalendarEvent
}

func (p *DeadlineDocument) GetTimestamp() (v string) {
	return p.Timestamp
}

func (p *DeadlineDocument) GetSubTasks() (v []*SubTask) {
	return p.SubTasks
}
func (p *DeadlineDocument) SetUid(val string) {
	p.Uid = val
}
func (p *DeadlineDocument) SetLegacyId(val int64) {
	p.LegacyId = val
}
func (p *DeadlineDocument) SetName(val string) {
	p.Name = val
}
func (p *DeadlineDocument) SetStartTime(val string) {
	p.StartTime = val
}
func (p *DeadlineDocument) SetEndTime(val string) {
	p.EndTime = val
}
func (p *DeadlineDocument) SetState(val string) {
	p.State = val
}
func (p *DeadlineDocument) SetCompleteTime(val string) {
	p.CompleteTime = val
}
func (p *DeadlineDocument) SetNote(val string) {
	p.Note = val
}
func (p *DeadlineDocument) SetIsStared(val bool) {
	p.IsStared = val
}
func (p *DeadlineDocument) SetType(val string) {
	p.Type = val
}
func (p *DeadlineDocument) SetHabitCount(val int32) {
	p.HabitCount = val
}
func (p *DeadlineDocument) SetHabitTotalCount(val int32) {
	p.HabitTotalCount = val
}
func (p *DeadlineDocument) SetCalendarEvent(val int64) {
	p.CalendarEvent = val
}
func (p *DeadlineDocument) SetTimestamp(val string) {
	p.Timestamp = val
}
func (p *DeadlineDocument) SetSubTasks(val []*SubTask) {
	p.SubTasks = val
}

func (p *DeadlineDocument) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeadlineDocument(%+v)", *p)
}

var fieldIDToName_DeadlineDocument = map[int16]string{
	1:  "uid",
	2:  "legacy_id",
	3:  "name",
	4:  "start_time",
	5:  "end_time",
	6:  "state",
	7:  "complete_time",
	8:  "note",
	9:  "is_stared",
	10: "type",
	11: "habit_count",
	12: "habit_total_count",
	13: "calendar_event",
	14: "timestamp",
	15: "sub_tasks",
}

type HabitConfig struct {
	Name           string `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Description    string `thrift:"description,2" frugal:"2,default,string" json:"description"`
	IconKey        string `thrift:"icon_key,4" frugal:"4,default,string" json:"icon_key"`
	Period         string `thrift:"period,5" frugal:"5,default,string" json:"period"`
	TimesPerPeriod int32  `thrift:"times_per_period,6" frugal:"6,default,i32" json:"times_per_period"`
	GoalType       string `thrift:"goal_type,7" frugal:"7,default,string" json:"goal_type"`
	TotalTarget    int32  `thrift:"total_target,8" frugal:"8,default,i32" json:"total_target"`
	CreatedAt      string `thrift:"created_at,9" frugal:"9,default,string" json:"created_at"`
	UpdatedAt      string `thrift:"updated_at,10" frugal:"10,default,string" json:"updated_at"`
	Status         string `thrift:"status,11" frugal:"11,default,string" json:"status"`
	SortOrder      int32  `thrift:"sort_order,12" frugal:"12,default,i32" json:"sort_order"`
	AlarmTime      string `thrift:"alarm_time,13" frugal:"13,default,string" json:"alarm_time"`
}

func NewHabitConfig() *HabitConfig {
	return &HabitConfig{}
}

func (p *HabitConfig) InitDefault() {
}

func (p *HabitConfig) GetName() (v string) {
	return p.Name
}

func (p *HabitConfig) GetDescription() (v string) {
	return p.Description
}

func (p *HabitConfig) GetIconKey() (v string) {
	return p.IconKey
}

func (p *HabitConfig) GetPeriod() (v string) {
	return p.Period
}

func (p *HabitConfig) GetTimesPerPeriod() (v int32) {
	return p.TimesPerPeriod
}

func (p *HabitConfig) GetGoalType() (v string) {
	return p.GoalType
}

func (p *HabitConfig) GetTotalTarget() (v int32) {
	return p.TotalTarget
}

func (p *HabitConfig) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *HabitConfig) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *HabitConfig) GetStatus() (v string) {
	return p.Status
}

func (p *HabitConfig) GetSortOrder() (v int32) {
	return p.SortOrder
}

func (p *HabitConfig) GetAlarmTime() (v string) {
	return p.AlarmTime
}
func (p *HabitConfig) SetName(val string) {
	p.Name = val
}
func (p *HabitConfig) SetDescription(val string) {
	p.Description = val
}
func (p *HabitConfig) SetIconKey(val string) {
	p.IconKey = val
}
func (p *HabitConfig) SetPeriod(val string) {
	p.Period = val
}
func (p *HabitConfig) SetTimesPerPeriod(val int32) {
	p.TimesPerPeriod = val
}
func (p *HabitConfig) SetGoalType(val string) {
	p.GoalType = val
}
func (p *HabitConfig) SetTotalTarget(val int32) {
	p.TotalTarget = val
}
func (p *HabitConfig) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *HabitConfig) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}
func (p *HabitConfig) SetStatus(val string) {
	p.Status = val
}
func (p *HabitConfig) SetSortOrder(val int32) {
	p.SortOrder = val
}
func (p *HabitConfig) SetAlarmTime(val string) {
	p.AlarmTime = val
}

func (p *HabitConfig) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HabitConfig(%+v)", *p)
}

var fieldIDToName_HabitConfig = map[int16]string{
	1:  "name",
	2:  "description",
	4:  "icon_key",
	5:  "period",
	6:  "times_per_period",
	7:  "goal_type",
	8:  "total_target",
	9:  "created_at",
	10: "updated_at",
	11: "status",
	12: "sort_order",
	13: "alarm_time",
}

type HabitRecord struct {
	Date      string `thrift:"date,1" frugal:"1,default,string" json:"date"`
	Count     int32  `thrift:"count,2" frugal:"2,default,i32" json:"count"`
	Status    string `thrift:"status,3" frugal:"3,default,string" json:"status"`
	CreatedAt string `thrift:"created_at,4" frugal:"4,default,string" json:"created_at"`
}

func NewHabitRecord() *HabitRecord {
	return &HabitRecord{}
}

func (p *HabitRecord) InitDefault() {
}

func (p *HabitRecord) GetDate() (v string) {
	return p.Date
}

func (p *HabitRecord) GetCount() (v int32) {
	return p.Count
}

func (p *HabitRecord) GetStatus() (v string) {
	return p.Status
}

func (p *HabitRecord) GetCreatedAt() (v string) {
	return p.CreatedAt
}
func (p *HabitRecord) SetDate(val string) {
	p.Date = val
}
func (p *HabitRecord) SetCount(val int32) {
	p.Count = val
}
func (p *HabitRecord) SetStatus(val string) {
	p.Status = val
}
func (p *HabitRecord) SetCreatedAt(val string) {
	p.CreatedAt = val
}

func (p *HabitRecord) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HabitRecord(%+v)", *p)
}

var fieldIDToName_HabitRecord = map[int16]string{
	1: "date",
	2: "count",
	3: "status",
	4: "created_at",
}

type HabitDocument struct {
	DdlUid  string         `thrift:"ddl_uid,1" frugal:"1,default,string" json:"ddl_uid"`
	Habit   *HabitConfig   `thrift:"habit,2" frugal:"2,default,HabitConfig" json:"habit"`
	Records []*HabitRecord `thrift:"records,3" frugal:"3,default,list<HabitRecord>" json:"records"`
}

func NewHabitDocument() *HabitDocument {
	return &HabitDocument{}
}

func (p *HabitDocument) InitDefault() {
}

func (p *HabitDocument) GetDdlUid() (v string) {
	return p.DdlUid
}

var HabitDocument_Habit_DEFAULT *HabitConfig

func (p *HabitDocument) GetHabit() (v *HabitConfig) {
	if !p.IsSetHabit() {
		return HabitDocument_Habit_DEFAULT
	}
	return p.Habit
}

func (p *HabitDocument) GetRecords() (v []*HabitRecord) {
	return p.Records
}
func (p *HabitDocument) SetDdlUid(val string) {
	p.DdlUid = val
}
func (p *HabitDocument) SetHabit(val *HabitConfig) {
	p.Habit = val
}
func (p *HabitDocument) SetRecords(val []*HabitRecord) {
	p.Records = val
}

func (p *HabitDocument) IsSetHabit() bool {
	return p.Habit != nil
}

func (p *HabitDocument) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HabitDocument(%+v)", *p)
}

var fieldIDToName_HabitDocument = map[int16]string{
	1: "ddl_uid",
	2: "habit",
	3: "records",
}

type DeadlineMutation struct {
	Deleted bool              `thrift:"deleted,1" frugal:"1,default,bool" json:"deleted"`
	Doc     *DeadlineDocument `thrift:"doc,2,optional" frugal:"2,optional,DeadlineDocument" json:"doc,omitempty"`
}

func NewDeadlineMutation() *DeadlineMutation {
	return &DeadlineMutation{}
}

func (p *DeadlineMutation) InitDefault() {
}

func (p *DeadlineMutation) GetDeleted() (v bool) {
	return p.Deleted
}

var DeadlineMutation_Doc_DEFAULT *DeadlineDocument

func (p *DeadlineMutation) GetDoc() (v *DeadlineDocument) {
	if !p.IsSetDoc() {
		return DeadlineMutation_Doc_DEFAULT
	}
	return p.Doc
}
func (p *DeadlineMutation) SetDeleted(val bool) {
	p.Deleted = val
}
func (p *DeadlineMutation) SetDoc(val *DeadlineDocument) {
	p.Doc = val
}

func (p *DeadlineMutation) IsSetDoc() bool {
	return p.Doc != nil
}

func (p *DeadlineMutation) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeadlineMutation(%+v)", *p)
}

var fieldIDToName_DeadlineMutation = map[int16]string{
	1: "deleted",
	2: "doc",
}

type HabitMutation struct {
	Deleted bool           `thrift:"deleted,1" frugal:"1,default,bool" json:"deleted"`
	Doc     *HabitDocument `thrift:"doc,2,optional" frugal:"2,optional,HabitDocument" json:"doc,omitempty"`
}

func NewHabitMutation() *HabitMutation {
	return &HabitMutation{}
}

func (p *HabitMutation) InitDefault() {
}

func (p *HabitMutation) GetDeleted() (v bool) {
	return p.Deleted
}

var HabitMutation_Doc_DEFAULT *HabitDocument

func (p *HabitMutation) GetDoc() (v *HabitDocument) {
	if !p.IsSetDoc() {
		return HabitMutation_Doc_DEFAULT
	}
	return p.Doc
}
func (p *HabitMutation) SetDeleted(val bool) {
	p.Deleted = val
}
func (p *HabitMutation) SetDoc(val *HabitDocument) {
	p.Doc = val
}

func (p *HabitMutation) IsSetDoc() bool {
	return p.Doc != nil
}

func (p *HabitMutation) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HabitMutation(%+v)", *p)
}

var fieldIDToName_HabitMutation = map[int16]string{
	1: "deleted",
	2: "doc",
}

type Mutation struct {
	MutationId    string           `thrift:"mutation_id,1" frugal:"1,default,string" json:"mutation_id"`
	DeviceUid     string           `thrift:"device_uid,2" frugal:"2,default,string" json:"device_uid"`
	EntityUid     string           `thrift:"entity_uid,3" frugal:"3,default,string" json:"entity_uid"`
	ClientVersion *ClientVersion   `thrift:"client_version,4" frugal:"4,default,ClientVersion" json:"client_version"`
	BaseChangeId  *int64           `thrift:"base_change_id,5,optional" frugal:"5,optional,i64" json:"base_change_id,omitempty"`
	Payload       *MutationPayload `thrift:"payload,6" frugal:"6,default,MutationPayload" json:"payload"`
}

func NewMutation() *Mutation {
	return &Mutation{}
}

func (p *Mutation) InitDefault() {
}

func (p *Mutation) GetMutationId() (v string) {
	return p.MutationId
}

func (p *Mutation) GetDeviceUid() (v string) {
	return p.DeviceUid
}

func (p *Mutation) GetEntityUid() (v string) {
	return p.EntityUid
}

var Mutation_ClientVersion_DEFAULT *ClientVersion

func (p *Mutation) GetClientVersion() (v *ClientVersion) {
	if !p.IsSetClientVersion() {
		return Mutation_ClientVersion_DEFAULT
	}
	return p.ClientVersion
}

var Mutation_BaseChangeId_DEFAULT int64

func (p *Mutation) GetBaseChangeId() (v int64) {
	if !p.IsSetBaseChangeId() {
		return Mutation_BaseChangeId_DEFAULT
	}
	return *p.BaseChangeId
}

var Mutation_Payload_DEFAULT *MutationPayload

func (p *Mutation) GetPayload() (v *MutationPayload) {
	if !p.IsSetPayload() {
		return Mutation_Payload_DEFAULT
	}
	return p.Payload
}
func (p *Mutation) SetMutationId(val string) {
	p.MutationId = val
}
func (p *Mutation) SetDeviceUid(val string) {
	p.DeviceUid = val
}
func (p *Mutation) SetEntityUid(val string) {
	p.EntityUid = val
}
func (p *Mutation) SetClientVersion(val *ClientVersion) {
	p.ClientVersion = val
}
func (p *Mutation) SetBaseChangeId(val *int64) {
	p.BaseChangeId = val
}
func (p *Mutation) SetPayload(val *MutationPayload) {
	p.Payload = val
}

func (p *Mutation) IsSetClientVersion() bool {
	return p.ClientVersion != nil
}

func (p *Mutation) IsSetBaseChangeId() bool {
	return p.BaseChangeId != nil
}

func (p *Mutation) IsSetPayload() bool {
	return p.Payload != nil
}

func (p *Mutation) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Mutation(%+v)", *p)
}

var fieldIDToName_Mutation = map[int16]string{
	1: "mutation_id",
	2: "device_uid",
	3: "entity_uid",
	4: "client_version",
	5: "base_change_id",
	6: "payload",
}

type MutationResult_ struct {
	MutationId      string         `thrift:"mutation_id,1" frugal:"1,default,string" json:"mutation_id"`
	EntityUid       string         `thrift:"entity_uid,2" frugal:"2,default,string" json:"entity_uid"`
	Accepted        bool           `thrift:"accepted,3" frugal:"3,default,bool" json:"accepted"`
	RejectionReason string         `thrift:"rejection_reason,4" frugal:"4,default,string" json:"rejection_reason"`
	ServerVersion   *ServerVersion `thrift:"server_version,5,optional" frugal:"5,optional,ServerVersion" json:"server_version,omitempty"`
	Replayed        bool           `thrift:"replayed,6" frugal:"6,default,bool" json:"replayed"`
	Status          *string        `thrift:"status,7,optional" frugal:"7,optional,string" json:"status,omitempty"`
}

func NewMutationResult_() *MutationResult_ {
	return &MutationResult_{}
}

func (p *MutationResult_) InitDefault() {
}

func (p *MutationResult_) GetMutationId() (v string) {
	return p.MutationId
}

func (p *MutationResult_) GetEntityUid() (v string) {
	return p.EntityUid
}

func (p *MutationResult_) GetAccepted() (v bool) {
	return p.Accepted
}

func (p *MutationResult_) GetRejectionReason() (v string) {
	return p.RejectionReason
}

var MutationResult__ServerVersion_DEFAULT *ServerVersion

func (p *MutationResult_) GetServerVersion() (v *ServerVersion) {
	if !p.IsSetServerVersion() {
		return MutationResult__ServerVersion_DEFAULT
	}
	return p.ServerVersion
}

func (p *MutationResult_) GetReplayed() (v bool) {
	return p.Replayed
}

var MutationResult__Status_DEFAULT string

func (p *MutationResult_) GetStatus() (v string) {
	if !p.IsSetStatus() {
		return MutationResult__Status_DEFAULT
	}
	return *p.Status
}
func (p *MutationResult_) SetMutationId(val string) {
	p.MutationId = val
}
func (p *MutationResult_) SetEntityUid(val string) {
	p.EntityUid = val
}
func (p *MutationResult_) SetAccepted(val bool) {
	p.Accepted = val
}
func (p *MutationResult_) SetRejectionReason(val string) {
	p.RejectionReason = val
}
func (p *MutationResult_) SetServerVersion(val *ServerVersion) {
	p.ServerVersion = val
}
func (p *MutationResult_) SetReplayed(val bool) {
	p.Replayed = val
}
func (p *MutationResult_) SetStatus(val *string) {
	p.Status = val
}

func (p *MutationResult_) IsSetServerVersion() bool {
	return p.ServerVersion != nil
}

func (p *MutationResult_) IsSetStatus() bool {
	return p.Status != nil
}

func (p *MutationResult_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MutationResult_(%+v)", *p)
}

var fieldIDToName_MutationResult_ = map[int16]string{
	1: "mutation_id",
	2: "entity_uid",
	3: "accepted",
	4: "rejection_reason",
	5: "server_version",
	6: "replayed",
	7: "status",
}

type DeadlineChange struct {
	EntityUid     string            `thrift:"entity_uid,1" frugal:"1,default,string" json:"entity_uid"`
	Deleted       bool              `thrift:"deleted,2" frugal:"2,default,bool" json:"deleted"`
	ServerVersion *ServerVersion    `thrift:"server_version,3" frugal:"3,default,ServerVersion" json:"server_version"`
	Doc           *DeadlineDocument `thrift:"doc,4,optional" frugal:"4,optional,DeadlineDocument" json:"doc,omitempty"`
}

func NewDeadlineChange() *DeadlineChange {
	return &DeadlineChange{}
}

func (p *DeadlineChange) InitDefault() {
}

func (p *DeadlineChange) GetEntityUid() (v string) {
	return p.EntityUid
}

func (p *DeadlineChange) GetDeleted() (v bool) {
	return p.Deleted
}

var DeadlineChange_ServerVersion_DEFAULT *ServerVersion

func (p *DeadlineChange) GetServerVersion() (v *ServerVersion) {
	if !p.IsSetServerVersion() {
		return DeadlineChange_ServerVersion_DEFAULT
	}
	return p.ServerVersion
}

var DeadlineChange_Doc_DEFAULT *DeadlineDocument

func (p *DeadlineChange) GetDoc() (v *DeadlineDocument) {
	if !p.IsSetDoc() {
		return DeadlineChange_Doc_DEFAULT
	}
	return p.Doc
}
func (p *DeadlineChange) SetEntityUid(val string) {
	p.EntityUid = val
}
func (p *DeadlineChange) SetDeleted(val bool) {
	p.Deleted = val
}
func (p *DeadlineChange) SetServerVersion(val *ServerVersion) {
	p.ServerVersion = val
}
func (p *DeadlineChange) SetDoc(val *DeadlineDocument) {
	p.Doc = val
}

func (p *DeadlineChange) IsSetServerVersion() bool {
	return p.ServerVersion != nil
}

func (p *DeadlineChange) IsSetDoc() bool {
	return p.Doc != nil
}

func (p *DeadlineChange) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeadlineChange(%+v)", *p)
}

var fieldIDToName_DeadlineChange = map[int16]string{
	1: "entity_uid",
	2: "deleted",
	3: "server_version",
	4: "doc",
}

type HabitChange struct {
	EntityUid     string         `thrift:"entity_uid,1" frugal:"1,default,string" json:"entity_uid"`
	Deleted       bool           `thrift:"deleted,2" frugal:"2,default,bool" json:"deleted"`
	ServerVersion *ServerVersion `thrift:"server_version,3" frugal:"3,default,ServerVersion" json:"server_version"`
	Doc           *HabitDocument `thrift:"doc,4,optional" frugal:"4,optional,HabitDocument" json:"doc,omitempty"`
}

func NewHabitChange() *HabitChange {
	return &HabitChange{}
}

func (p *HabitChange) InitDefault() {
}

func (p *HabitChange) GetEntityUid() (v string) {
	return p.EntityUid
}

func (p *HabitChange) GetDeleted() (v bool) {
	return p.Deleted
}

var HabitChange_ServerVersion_DEFAULT *ServerVersion

func (p *HabitChange) GetServerVersion() (v *ServerVersion) {
	if !p.IsSetServerVersion() {
		return HabitChange_ServerVersion_DEFAULT
	}
	return p.ServerVersion
}

var HabitChange_Doc_DEFAULT *HabitDocument

func (p *HabitChange) GetDoc() (v *HabitDocument) {
	if !p.IsSetDoc() {
		return HabitChange_Doc_DEFAULT
	}
	return p.Doc
}
func (p *HabitChange) SetEntityUid(val string) {
	p.EntityUid = val
}
func (p *HabitChange) SetDeleted(val bool) {
	p.Deleted = val
}
func (p *HabitChange) SetServerVersion(val *ServerVersion) {
	p.ServerVersion = val
}
func (p *HabitChange) SetDoc(val *HabitDocument) {
	p.Doc = val
}

func (p *HabitChange) IsSetServerVersion() bool {
	return p.ServerVersion != nil
}

func (p *HabitChange) IsSetDoc() bool {
	return p.Doc != nil
}

func (p *HabitChange) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HabitChange(%+v)", *p)
}

var fieldIDToName_HabitChange = map[int16]string{
	1: "entity_uid",
	2: "deleted",
	3: "server_version",
	4: "doc",
}

type PullChangesRequest struct {
	DeviceUid      string `thrift:"device_uid,1" frugal:"1,default,string" json:"device_uid"`
	Cursor         string `thrift:"cursor,2" frugal:"2,default,string" json:"cursor"`
	Limit          int32  `thrift:"limit,3" frugal:"3,default,i32" json:"limit"`
	IncludeDeleted bool   `thrift:"include_deleted,4" frugal:"4,default,bool" json:"include_deleted"`
}

func NewPullChangesRequest() *PullChangesRequest {
	return &PullChangesRequest{}
}

func (p *PullChangesRequest) InitDefault() {
}

func (p *PullChangesRequest) GetDeviceUid() (v string) {
	return p.DeviceUid
}

func (p *PullChangesRequest) GetCursor() (v string) {
	return p.Cursor
}

func (p *PullChangesRequest) GetLimit() (v int32) {
	return p.Limit
}

func (p *PullChangesRequest) GetIncludeDeleted() (v bool) {
	return p.IncludeDeleted
}
func (p *PullChangesRequest) SetDeviceUid(val string) {
	p.DeviceUid = val
}
func (p *PullChangesRequest) SetCursor(val string) {
	p.Cursor = val
}
func (p *PullChangesRequest) SetLimit(val int32) {
	p.Limit = val
}
func (p *PullChangesRequest) SetIncludeDeleted(val bool) {
	p.IncludeDeleted = val
}

func (p *PullChangesRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PullChangesRequest(%+v)", *p)
}

var fieldIDToName_PullChangesRequest = map[int16]string{
	1: "device_uid",
	2: "cursor",
	3: "limit",
	4: "include_deleted",
}

type PullChangesResponse struct {
	DeadlineChanges []*DeadlineChange `thrift:"deadline_changes,1" frugal:"1,default,list<DeadlineChange>" json:"deadline_changes"`
	HabitChanges    []*HabitChange    `thrift:"habit_changes,2" frugal:"2,default,list<HabitChange>" json:"habit_changes"`
	NextCursor      string            `thrift:"next_cursor,3" frugal:"3,default,string" json:"next_cursor"`
	HasMore         bool              `thrift:"has_more,4" frugal:"4,default,bool" json:"has_more"`
}

func NewPullChangesResponse() *PullChangesResponse {
	return &PullChangesResponse{}
}

func (p *PullChangesResponse) InitDefault() {
}

func (p *PullChangesResponse) GetDeadlineChanges() (v []*DeadlineChange) {
	return p.DeadlineChanges
}

func (p *PullChangesResponse) GetHabitChanges() (v []*HabitChange) {
	return p.HabitChanges
}

func (p *PullChangesResponse) GetNextCursor() (v string) {
	return p.NextCursor
}

func (p *PullChangesResponse) GetHasMore() (v bool) {
	return p.HasMore
}
func (p *PullChangesResponse) SetDeadlineChanges(val []*DeadlineChange) {
	p.DeadlineChanges = val
}
func (p *PullChangesResponse) SetHabitChanges(val []*HabitChange) {
	p.HabitChanges = val
}
func (p *PullChangesResponse) SetNextCursor(val string) {
	p.NextCursor = val
}
func (p *PullChangesResponse) SetHasMore(val bool) {
	p.HasMore = val
}

func (p *PullChangesResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PullChangesResponse(%+v)", *p)
}

var fieldIDToName_PullChangesResponse = map[int16]string{
	1: "deadline_changes",
	2: "habit_changes",
	3: "next_cursor",
	4: "has_more",
}

type PushChangesRequest struct {
	DeviceUid  string      `thrift:"device_uid,1" frugal:"1,default,string" json:"device_uid"`
	BaseCursor string      `thrift:"base_cursor,2" frugal:"2,default,string" json:"base_cursor"`
	Mutations  []*Mutation `thrift:"mutations,3" frugal:"3,default,list<Mutation>" json:"mutations"`
}

func NewPushChangesRequest() *PushChangesRequest {
	return &PushChangesRequest{}
}

func (p *PushChangesRequest) InitDefault() {
}

func (p *PushChangesRequest) GetDeviceUid() (v string) {
	return p.DeviceUid
}

func (p *PushChangesRequest) GetBaseCursor() (v string) {
	return p.BaseCursor
}

func (p *PushChangesRequest) GetMutations() (v []*Mutation) {
	return p.Mutations
}
func (p *PushChangesRequest) SetDeviceUid(val string) {
	p.DeviceUid = val
}
func (p *PushChangesRequest) SetBaseCursor(val string) {
	p.BaseCursor = val
}
func (p *PushChangesRequest) SetMutations(val []*Mutation) {
	p.Mutations = val
}

func (p *PushChangesRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PushChangesRequest(%+v)", *p)
}

var fieldIDToName_PushChangesRequest = map[int16]string{
	1: "device_uid",
	2: "base_cursor",
	3: "mutations",
}

type PushChangesResponse struct {
	Results         []*MutationResult_ `thrift:"results,1" frugal:"1,default,list<MutationResult_>" json:"results"`
	DeadlineChanges []*DeadlineChange  `thrift:"deadline_changes,2" frugal:"2,default,list<DeadlineChange>" json:"deadline_changes"`
	HabitChanges    []*HabitChange     `thrift:"habit_changes,3" frugal:"3,default,list<HabitChange>" json:"habit_changes"`
	NextCursor      string             `thrift:"next_cursor,4" frugal:"4,default,string" json:"next_cursor"`
}

func NewPushChangesResponse() *PushChangesResponse {
	return &PushChangesResponse{}
}

func (p *PushChangesResponse) InitDefault() {
}

func (p *PushChangesResponse) GetResults() (v []*MutationResult_) {
	return p.Results
}

func (p *PushChangesResponse) GetDeadlineChanges() (v []*DeadlineChange) {
	return p.DeadlineChanges
}

func (p *PushChangesResponse) GetHabitChanges() (v []*HabitChange) {
	return p.HabitChanges
}

func (p *PushChangesResponse) GetNextCursor() (v string) {
	return p.NextCursor
}
func (p *PushChangesResponse) SetResults(val []*MutationResult_) {
	p.Results = val
}
func (p *PushChangesResponse) SetDeadlineChanges(val []*DeadlineChange) {
	p.DeadlineChanges = val
}
func (p *PushChangesResponse) SetHabitChanges(val []*HabitChange) {
	p.HabitChanges = val
}
func (p *PushChangesResponse) SetNextCursor(val string) {
	p.NextCursor = val
}

func (p *PushChangesResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PushChangesResponse(%+v)", *p)
}

var fieldIDToName_PushChangesResponse = map[int16]string{
	1: "results",
	2: "deadline_changes",
	3: "habit_changes",
	4: "next_cursor",
}

type MutationPayload struct {
	Deadline *DeadlineMutation `thrift:"deadline,1,optional" frugal:"1,optional,DeadlineMutation" json:"deadline,omitempty"`
	Habit    *HabitMutation    `thrift:"habit,2,optional" frugal:"2,optional,HabitMutation" json:"habit,omitempty"`
}

func NewMutationPayload() *MutationPayload {
	return &MutationPayload{}
}

func (p *MutationPayload) InitDefault() {
}

var MutationPayload_Deadline_DEFAULT *DeadlineMutation

func (p *MutationPayload) GetDeadline() (v *DeadlineMutation) {
	if !p.IsSetDeadline() {
		return MutationPayload_Deadline_DEFAULT
	}
	return p.Deadline
}

var MutationPayload_Habit_DEFAULT *HabitMutation

func (p *MutationPayload) GetHabit() (v *HabitMutation) {
	if !p.IsSetHabit() {
		return MutationPayload_Habit_DEFAULT
	}
	return p.Habit
}
func (p *MutationPayload) SetDeadline(val *DeadlineMutation) {
	p.Deadline = val
}
func (p *MutationPayload) SetHabit(val *HabitMutation) {
	p.Habit = val
}

func (p *MutationPayload) CountSetFieldsMutationPayload() int {
	count := 0
	if p.IsSetDeadline() {
		count++
	}
	if p.IsSetHabit() {
		count++
	}
	return count
}

func (p *MutationPayload) IsSetDeadline() bool {
	return p.Deadline != nil
}

func (p *MutationPayload) IsSetHabit() bool {
	return p.Habit != nil
}

func (p *MutationPayload) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MutationPayload(%+v)", *p)
}

var fieldIDToName_MutationPayload = map[int16]string{
	1: "deadline",
	2: "habit",
}

type DeadlinerService interface {
	Register(ctx context.Context, req *RegisterRequest) (r *RegisterResponse, err error)

	Login(ctx context.Context, req *LoginRequest) (r *LoginResponse, err error)

	RefreshSession(ctx context.Context, req *RefreshSessionRequest) (r *RefreshSessionResponse, err error)

	PullChanges(ctx context.Context, req *PullChangesRequest) (r *PullChangesResponse, err error)

	PushChanges(ctx context.Context, req *PushChangesRequest) (r *PushChangesResponse, err error)
}

type DeadlinerServiceRegisterArgs struct {
	Req *RegisterRequest `thrift:"req,1" frugal:"1,default,RegisterRequest" json:"req"`
}

func NewDeadlinerServiceRegisterArgs() *DeadlinerServiceRegisterArgs {
	return &DeadlinerServiceRegisterArgs{}
}

func (p *DeadlinerServiceRegisterArgs) InitDefault() {
}

var DeadlinerServiceRegisterArgs_Req_DEFAULT *RegisterRequest

func (p *DeadlinerServiceRegisterArgs) GetReq() (v *RegisterRequest) {
	if !p.IsSetReq() {
		return DeadlinerServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DeadlinerServiceRegisterArgs) SetReq(val *RegisterRequest) {
	p.Req = val
}

func (p *DeadlinerServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeadlinerServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeadlinerServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_DeadlinerServiceRegisterArgs = map[int16]string{
	1: "req",
}

type DeadlinerServiceRegisterResult struct {
	Success *RegisterResponse `thrift:"success,0,optional" frugal:"0,optional,RegisterResponse" json:"success,omitempty"`
}

func NewDeadlinerServiceRegisterResult() *DeadlinerServiceRegisterResult {
	return &DeadlinerServiceRegisterResult{}
}

func (p *DeadlinerServiceRegisterResult) InitDefault() {
}

var DeadlinerServiceRegisterResult_Success_DEFAULT *RegisterResponse

func (p *DeadlinerServiceRegisterResult) GetSuccess() (v *RegisterResponse) {
	if !p.IsSetSuccess() {
		return DeadlinerServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DeadlinerServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResponse)
}

func (p *DeadlinerServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeadlinerServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeadlinerServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_DeadlinerServiceRegisterResult = map[int16]string{
	0: "success",
}

type DeadlinerServiceLoginArgs struct {
	Req *LoginRequest `thrift:"req,1" frugal:"1,default,LoginRequest" json:"req"`
}

func NewDeadlinerServiceLoginArgs() *DeadlinerServiceLoginArgs {
	return &DeadlinerServiceLoginArgs{}
}

func (p *DeadlinerServiceLoginArgs) InitDefault() {
}

var DeadlinerServiceLoginArgs_Req_DEFAULT *LoginRequest

func (p *DeadlinerServiceLoginArgs) GetReq() (v *LoginRequest) {
	if !p.IsSetReq() {
		return DeadlinerServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DeadlinerServiceLoginArgs) SetReq(val *LoginRequest) {
	p.Req = val
}

func (p *DeadlinerServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeadlinerServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeadlinerServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_DeadlinerServiceLoginArgs = map[int16]string{
	1: "req",
}

type DeadlinerServiceLoginResult struct {
	Success *LoginResponse `thrift:"success,0,optional" frugal:"0,optional,LoginResponse" json:"success,omitempty"`
}

func NewDeadlinerServiceLoginResult() *DeadlinerServiceLoginResult {
	return &DeadlinerServiceLoginResult{}
}

func (p *DeadlinerServiceLoginResult) InitDefault() {
}

var DeadlinerServiceLoginResult_Success_DEFAULT *LoginResponse

func (p *DeadlinerServiceLoginResult) GetSuccess() (v *LoginResponse) {
	if !p.IsSetSuccess() {
		return DeadlinerServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DeadlinerServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResponse)
}

func (p *DeadlinerServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeadlinerServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeadlinerServiceLoginResult(%+v)", *p)
}

var fieldIDToName_DeadlinerServiceLoginResult = map[int16]string{
	0: "success",
}

type DeadlinerServiceRefreshSessionArgs struct {
	Req *RefreshSessionRequest `thrift:"req,1" frugal:"1,default,RefreshSessionRequest" json:"req"`
}

func NewDeadlinerServiceRefreshSessionArgs() *DeadlinerServiceRefreshSessionArgs {
	return &DeadlinerServiceRefreshSessionArgs{}
}

func (p *DeadlinerServiceRefreshSessionArgs) InitDefault() {
}

var DeadlinerServiceRefreshSessionArgs_Req_DEFAULT *RefreshSessionRequest

func (p *DeadlinerServiceRefreshSessionArgs) GetReq() (v *RefreshSessionRequest) {
	if !p.IsSetReq() {
		return DeadlinerServiceRefreshSessionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DeadlinerServiceRefreshSessionArgs) SetReq(val *RefreshSessionRequest) {
	p.Req = val
}

func (p *DeadlinerServiceRefreshSessionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeadlinerServiceRefreshSessionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeadlinerServiceRefreshSessionArgs(%+v)", *p)
}

var fieldIDToName_DeadlinerServiceRefreshSessionArgs = map[int16]string{
	1: "req",
}

type DeadlinerServiceRefreshSessionResult struct {
	Success *RefreshSessionResponse `thrift:"success,0,optional" frugal:"0,optional,RefreshSessionResponse" json:"success,omitempty"`
}

func NewDeadlinerServiceRefreshSessionResult() *DeadlinerServiceRefreshSessionResult {
	return &DeadlinerServiceRefreshSessionResult{}
}

func (p *DeadlinerServiceRefreshSessionResult) InitDefault() {
}

var DeadlinerServiceRefreshSessionResult_Success_DEFAULT *RefreshSessionResponse

func (p *DeadlinerServiceRefreshSessionResult) GetSuccess() (v *RefreshSessionResponse) {
	if !p.IsSetSuccess() {
		return DeadlinerServiceRefreshSessionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DeadlinerServiceRefreshSessionResult) SetSuccess(x interface{}) {
	p.Success = x.(*RefreshSessionResponse)
}

func (p *DeadlinerServiceRefreshSessionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeadlinerServiceRefreshSessionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeadlinerServiceRefreshSessionResult(%+v)", *p)
}

var fieldIDToName_DeadlinerServiceRefreshSessionResult = map[int16]string{
	0: "success",
}

type DeadlinerServicePullChangesArgs struct {
	Req *PullChangesRequest `thrift:"req,1" frugal:"1,default,PullChangesRequest" json:"req"`
}

func NewDeadlinerServicePullChangesArgs() *DeadlinerServicePullChangesArgs {
	return &DeadlinerServicePullChangesArgs{}
}

func (p *DeadlinerServicePullChangesArgs) InitDefault() {
}

var DeadlinerServicePullChangesArgs_Req_DEFAULT *PullChangesRequest

func (p *DeadlinerServicePullChangesArgs) GetReq() (v *PullChangesRequest) {
	if !p.IsSetReq() {
		return DeadlinerServicePullChangesArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DeadlinerServicePullChangesArgs) SetReq(val *PullChangesRequest) {
	p.Req = val
}

func (p *DeadlinerServicePullChangesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeadlinerServicePullChangesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeadlinerServicePullChangesArgs(%+v)", *p)
}

var fieldIDToName_DeadlinerServicePullChangesArgs = map[int16]string{
	1: "req",
}

type DeadlinerServicePullChangesResult struct {
	Success *PullChangesResponse `thrift:"success,0,optional" frugal:"0,optional,PullChangesResponse" json:"success,omitempty"`
}

func NewDeadlinerServicePullChangesResult() *DeadlinerServicePullChangesResult {
	return &DeadlinerServicePullChangesResult{}
}

func (p *DeadlinerServicePullChangesResult) InitDefault() {
}

var DeadlinerServicePullChangesResult_Success_DEFAULT *PullChangesResponse

func (p *DeadlinerServicePullChangesResult) GetSuccess() (v *PullChangesResponse) {
	if !p.IsSetSuccess() {
		return DeadlinerServicePullChangesResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DeadlinerServicePullChangesResult) SetSuccess(x interface{}) {
	p.Success = x.(*PullChangesResponse)
}

func (p *DeadlinerServicePullChangesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeadlinerServicePullChangesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeadlinerServicePullChangesResult(%+v)", *p)
}

var fieldIDToName_DeadlinerServicePullChangesResult = map[int16]string{
	0: "success",
}

type DeadlinerServicePushChangesArgs struct {
	Req *PushChangesRequest `thrift:"req,1" frugal:"1,default,PushChangesRequest" json:"req"`
}

func NewDeadlinerServicePushChangesArgs() *DeadlinerServicePushChangesArgs {
	return &DeadlinerServicePushChangesArgs{}
}

func (p *DeadlinerServicePushChangesArgs) InitDefault() {
}

var DeadlinerServicePushChangesArgs_Req_DEFAULT *PushChangesRequest

func (p *DeadlinerServicePushChangesArgs) GetReq() (v *PushChangesRequest) {
	if !p.IsSetReq() {
		return DeadlinerServicePushChangesArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DeadlinerServicePushChangesArgs) SetReq(val *PushChangesRequest) {
	p.Req = val
}

func (p *DeadlinerServicePushChangesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeadlinerServicePushChangesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeadlinerServicePushChangesArgs(%+v)", *p)
}

var fieldIDToName_DeadlinerServicePushChangesArgs = map[int16]string{
	1: "req",
}

type DeadlinerServicePushChangesResult struct {
	Success *PushChangesResponse `thrift:"success,0,optional" frugal:"0,optional,PushChangesResponse" json:"success,omitempty"`
}

func NewDeadlinerServicePushChangesResult() *DeadlinerServicePushChangesResult {
	return &DeadlinerServicePushChangesResult{}
}

func (p *DeadlinerServicePushChangesResult) InitDefault() {
}

var DeadlinerServicePushChangesResult_Success_DEFAULT *PushChangesResponse

func (p *DeadlinerServicePushChangesResult) GetSuccess() (v *PushChangesResponse) {
	if !p.IsSetSuccess() {
		return DeadlinerServicePushChangesResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DeadlinerServicePushChangesResult) SetSuccess(x interface{}) {
	p.Success = x.(*PushChangesResponse)
}

func (p *DeadlinerServicePushChangesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeadlinerServicePushChangesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeadlinerServicePushChangesResult(%+v)", *p)
}

var fieldIDToName_DeadlinerServicePushChangesResult = map[int16]string{
	0: "success",
}
