// Code generated by Kitex v0.16.2. DO NOT EDIT.

package deadlinerservice

import (
	"context"
	v1 "github.com/aritxonly/deadlinerserver/kitex_gen/deadliner/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *v1.RegisterRequest, callOptions ...callopt.Option) (r *v1.RegisterResponse, err error)
	Login(ctx context.Context, req *v1.LoginRequest, callOptions ...callopt.Option) (r *v1.LoginResponse, err error)
	RefreshSession(ctx context.Context, req *v1.RefreshSessionRequest, callOptions ...callopt.Option) (r *v1.RefreshSessionResponse, err error)
	PullChanges(ctx context.Context, req *v1.PullChangesRequest, callOptions ...callopt.Option) (r *v1.PullChangesResponse, err error)
	PushChanges(ctx context.Context, req *v1.PushChangesRequest, callOptions ...callopt.Option) (r *v1.PushChangesResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kDeadlinerServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDeadlinerServiceClient struct {
	*kClient
}

func (p *kDeadlinerServiceClient) Register(ctx context.Context, req *v1.RegisterRequest, callOptions ...callopt.Option) (r *v1.RegisterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kDeadlinerServiceClient) Login(ctx context.Context, req *v1.LoginRequest, callOptions ...callopt.Option) (r *v1.LoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kDeadlinerServiceClient) RefreshSession(ctx context.Context, req *v1.RefreshSessionRequest, callOptions ...callopt.Option) (r *v1.RefreshSessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefreshSession(ctx, req)
}

func (p *kDeadlinerServiceClient) PullChanges(ctx context.Context, req *v1.PullChangesRequest, callOptions ...callopt.Option) (r *v1.PullChangesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PullChanges(ctx, req)
}

func (p *kDeadlinerServiceClient) PushChanges(ctx context.Context, req *v1.PushChangesRequest, callOptions ...callopt.Option) (r *v1.PushChangesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PushChanges(ctx, req)
}
