// Code generated by Kitex v0.16.2. DO NOT EDIT.

package deadlinerservice

import (
	"context"
	"errors"
	v1 "github.com/aritxonly/deadlinerserver/kitex_gen/deadliner/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newDeadlinerServiceRegisterArgs,
		newDeadlinerServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newDeadlinerServiceLoginArgs,
		newDeadlinerServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefreshSession": kitex.NewMethodInfo(
		refreshSessionHandler,
		newDeadlinerServiceRefreshSessionArgs,
		newDeadlinerServiceRefreshSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PullChanges": kitex.NewMethodInfo(
		pullChangesHandler,
		newDeadlinerServicePullChangesArgs,
		newDeadlinerServicePullChangesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PushChanges": kitex.NewMethodInfo(
		pushChangesHandler,
		newDeadlinerServicePushChangesArgs,
		newDeadlinerServicePushChangesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	deadlinerServiceServiceInfo                = NewServiceInfo()
	deadlinerServiceServiceInfoForClient       = NewServiceInfoForClient()
	deadlinerServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return deadlinerServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return deadlinerServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return deadlinerServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "DeadlinerService"
	handlerType := (*v1.DeadlinerService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*v1.DeadlinerServiceRegisterArgs)
	realResult := result.(*v1.DeadlinerServiceRegisterResult)
	success, err := handler.(v1.DeadlinerService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDeadlinerServiceRegisterArgs() interface{} {
	return v1.NewDeadlinerServiceRegisterArgs()
}

func newDeadlinerServiceRegisterResult() interface{} {
	return v1.NewDeadlinerServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*v1.DeadlinerServiceLoginArgs)
	realResult := result.(*v1.DeadlinerServiceLoginResult)
	success, err := handler.(v1.DeadlinerService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDeadlinerServiceLoginArgs() interface{} {
	return v1.NewDeadlinerServiceLoginArgs()
}

func newDeadlinerServiceLoginResult() interface{} {
	return v1.NewDeadlinerServiceLoginResult()
}

func refreshSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*v1.DeadlinerServiceRefreshSessionArgs)
	realResult := result.(*v1.DeadlinerServiceRefreshSessionResult)
	success, err := handler.(v1.DeadlinerService).RefreshSession(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDeadlinerServiceRefreshSessionArgs() interface{} {
	return v1.NewDeadlinerServiceRefreshSessionArgs()
}

func newDeadlinerServiceRefreshSessionResult() interface{} {
	return v1.NewDeadlinerServiceRefreshSessionResult()
}

func pullChangesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*v1.DeadlinerServicePullChangesArgs)
	realResult := result.(*v1.DeadlinerServicePullChangesResult)
	success, err := handler.(v1.DeadlinerService).PullChanges(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDeadlinerServicePullChangesArgs() interface{} {
	return v1.NewDeadlinerServicePullChangesArgs()
}

func newDeadlinerServicePullChangesResult() interface{} {
	return v1.NewDeadlinerServicePullChangesResult()
}

func pushChangesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*v1.DeadlinerServicePushChangesArgs)
	realResult := result.(*v1.DeadlinerServicePushChangesResult)
	success, err := handler.(v1.DeadlinerService).PushChanges(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDeadlinerServicePushChangesArgs() interface{} {
	return v1.NewDeadlinerServicePushChangesArgs()
}

func newDeadlinerServicePushChangesResult() interface{} {
	return v1.NewDeadlinerServicePushChangesResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *v1.RegisterRequest) (r *v1.RegisterResponse, err error) {
	var _args v1.DeadlinerServiceRegisterArgs
	_args.Req = req
	var _result v1.DeadlinerServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *v1.LoginRequest) (r *v1.LoginResponse, err error) {
	var _args v1.DeadlinerServiceLoginArgs
	_args.Req = req
	var _result v1.DeadlinerServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefreshSession(ctx context.Context, req *v1.RefreshSessionRequest) (r *v1.RefreshSessionResponse, err error) {
	var _args v1.DeadlinerServiceRefreshSessionArgs
	_args.Req = req
	var _result v1.DeadlinerServiceRefreshSessionResult
	if err = p.c.Call(ctx, "RefreshSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PullChanges(ctx context.Context, req *v1.PullChangesRequest) (r *v1.PullChangesResponse, err error) {
	var _args v1.DeadlinerServicePullChangesArgs
	_args.Req = req
	var _result v1.DeadlinerServicePullChangesResult
	if err = p.c.Call(ctx, "PullChanges", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PushChanges(ctx context.Context, req *v1.PushChangesRequest) (r *v1.PushChangesResponse, err error) {
	var _args v1.DeadlinerServicePushChangesArgs
	_args.Req = req
	var _result v1.DeadlinerServicePushChangesResult
	if err = p.c.Call(ctx, "PushChanges", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
